### ISSUE TITLE
One vertex too many created

### ISSUE THREAD

**Issue by jenscram** [farkhor/PaRMAT#4] opened 2016-02-18 09:14 UTC
Hi,

first of all thanks for this very useful R-MAT generator! I stumbled upon the following issue:

When creating a graph it seems that one more vertex than specified is created. Using the following command:

./PaRMAT -nEdges 1000 -nVertices 100 -sorted -a 0.25 -b 0.25 -c 0.25

(i.e. with equal edge distribution) will create edges containing vertices from 0 to 100 (both inclusive). Those are 101 vertices and not 100 as specified.

I hope this description is useful.

**Comment by farkhor** [comment] 2016-02-18 17:39
Thanks for catching this. The issue is now fixed.

**Closed** 2016-02-18 17:40 UTC
Labels: bug
